apiVersion: v1
kind: Service
metadata:
  name: oil-spill-detection
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: # Replace with your subnet IDs
      "subnet-0bb1c79de3EXAMPLE,subnet-0bb1c79de4EXAMPLE"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"    
spec:
  type: LoadBalancer
  selector:
    app: oil-spill-detection
  ports:
    - protocol: TCP
      port: 9696
      targetPort: 8080
