apiVersion: v1
kind: Service
metadata:
  name: oil_spill_detection
spec:
  type: NodePort
  selector:
    app: oil_spill_detection
  ports:
  - protocol: TCP
    port: 9696
    targetPort: 8080
    nodePort: 30080
